### ISSUE TITLE
Handling of reserved prefixes

### ISSUE THREAD

**Issue by dauwhe** [w3c/publ-cg#8] opened 2017-05-25 15:47 UTC
From Makoto via [email](https://lists.w3.org/Archives/Public/public-epub3/2017May/0015.html):

Apple iBook does not recognize a reserved prefix(*) which was
introduced in EPUB 3.0.1.  If this prefix is explicitly declared,
iBook has no problems in handling it.  But if it is not, iBook reports
an error.  Since this prefix is predefined in EPUB 3.0.1, this
behaviour does not conform to 3.0.1.  Apple turned down the request by
KADOKAWA to change this behavior.

* http://www.idpf.org/epub/301/spec/epub-publications.html#sec-metadata-reserved-vocabs

I am personally sympathetic to Apple, as additions of reserved
prefixes causes troubles to existing RSs.  I thus propose to add 
a warning about this issue and a recommendation to explicit 
declare this prefix by publishing an erratum to EPUB 3.0.1 and 3.1.

I hope that this topic can be discussed in the CG.

**Comment by mattgarrish** [comment] 2018-05-11 01:32
Isn't this a duplicate of https://github.com/w3c/publ-epub-revision/issues/974 ?

**Closed** 2019-04-30 19:33 UTC
Labels: Maintenance
